# Generated by Django 3.0.5 on 2020-07-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='username',
        ),
    ]
