# Generated by Django 3.0.5 on 2020-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20200722_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
    ]
