# Generated by Django 3.0.8 on 2020-07-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20200723_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
