# Generated by Django 3.0.8 on 2020-07-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
