# Generated by Django 3.0.8 on 2020-07-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200712_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
