# Generated by Django 3.0.5 on 2020-07-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_slug'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewPost',
            new_name='GadgetPost',
        ),
    ]
