# Generated by Django 3.0.5 on 2020-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200719_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='gadgetpost',
            name='categories',
            field=models.ManyToManyField(to='reviews.Categorey'),
        ),
    ]
