# Generated by Django 3.0.5 on 2020-07-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200719_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategorey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlemain', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='gadgetpost',
            name='maincategories',
            field=models.ManyToManyField(to='reviews.MainCategorey'),
        ),
    ]
