# Generated by Django 3.0.5 on 2020-07-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_softwarepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftwarePost',
        ),
    ]
