# Generated by Django 3.0.5 on 2020-07-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20200720_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorey',
            new_name='GadgetCategorey',
        ),
        migrations.RenameField(
            model_name='gadgetpost',
            old_name='categories',
            new_name='gadgetcategories',
        ),
    ]
